[package]
name = "bin2dec"
version = "0.1.0"
authors = ["assLlj <2358500119@qq.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
